version: "3"
services:
  python:
    build: .

  app:
    image: flask-template_python:latest
    ports:
     - 5000:5000
    volumes:
     - ./application:/src/application
     - ./foo.sqlite:/src/foo.sqlite
    working_dir: /src/
    environment:
      PYTHONPATH: /src
      FLASK_APP: application
      FLASK_DEBUG: "true"
    env_file:
      - credentials.env
    command: ["flask", "run", "--host=0.0.0.0"]